[tool.poetry]
name = "data-factory"
version = "0.1.3"
description = "data factory"
authors = ["Pedro"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
poetry = "^1.7.1"
pytest = "^8.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
