name: Pylint and Pytest

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv .venv
          source .venv/bin/activate
          pip install pylint==3.0.4
          pip install poetry
          poetry install
      - name: Check Python syntax
        run: |
          find . -name '*.py' -exec python -m py_compile {} +
      - name: Analysing the code with pylint
        run: |
          pylint --disable=R,C0301 $(git ls-files '*.py')
      - name: Run pytest
        run: |
          pytest